# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.process import Process  # noqa: F401,E501
from swagger_server import util


class Processes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, list_of_process: List[Process]=None):  # noqa: E501
        """Processes - a model defined in Swagger

        :param list_of_process: The list_of_process of this Processes.  # noqa: E501
        :type list_of_process: List[Process]
        """
        self.swagger_types = {
            'list_of_process': List[Process]
        }

        self.attribute_map = {
            'list_of_process': 'list_of_Process'
        }

        self._list_of_process = list_of_process

    @classmethod
    def from_dict(cls, dikt) -> 'Processes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Processes of this Processes.  # noqa: E501
        :rtype: Processes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def list_of_process(self) -> List[Process]:
        """Gets the list_of_process of this Processes.


        :return: The list_of_process of this Processes.
        :rtype: List[Process]
        """
        return self._list_of_process

    @list_of_process.setter
    def list_of_process(self, list_of_process: List[Process]):
        """Sets the list_of_process of this Processes.


        :param list_of_process: The list_of_process of this Processes.
        :type list_of_process: List[Process]
        """
        if list_of_process is None:
            raise ValueError("Invalid value for `list_of_process`, must not be `None`")  # noqa: E501

        self._list_of_process = list_of_process
